[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
enum-iterator = "1.2.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.7.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "find_win"
harness = false
